//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaServicio
    {
        public int nroLinea { get; set; }
        public int cantidad { get; set; }
        public float constoServicio { get; set; }
        public int alojamiento { get; set; }
        public int servicio { get; set; }
    
        public virtual Alojamiento Alojamiento1 { get; set; }
        public virtual Servicio Servicio1 { get; set; }
    }
}
