//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idPago { get; set; }
        public string tipo { get; set; }
        public float monto { get; set; }
        public System.DateTime fechaPago { get; set; }
        public string detalle { get; set; }
        public int alojamiento { get; set; }
    
        public virtual Alojamiento Alojamiento1 { get; set; }
    }
}
