//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamiento()
        {
            this.LineaServicio = new HashSet<LineaServicio>();
            this.Pago = new HashSet<Pago>();
        }
    
        public int idAlojamiento { get; set; }
        public int dniTitular { get; set; }
        public Nullable<System.DateTime> fechaReserva { get; set; }
        public System.DateTime fechaEstimadaIngreso { get; set; }
        public System.DateTime fechaEstimadaEgreso { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaEgreso { get; set; }
        public float montoTotal { get; set; }
        public float montoDeuda { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Habitacion Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaServicio> LineaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
