//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public int idDomicilio { get; set; }
        public string calle { get; set; }
        public int numero { get; set; }
        public int piso { get; set; }
        public int nroDpto { get; set; }
    }
}
